# Generated by Django 2.2.28 on 2022-08-31 09:01

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('democracy', '0058_poll_answer_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Action')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('action_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizationlog_action_by', to=settings.AUTH_USER_MODEL, verbose_name='action by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_log', to='democracy.Organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'organization log',
                'verbose_name_plural': 'organization logs',
            },
        ),
    ]
