# Generated by Django 2.2.28 on 2022-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerrokantasi', '0004_auto_20200225_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notified_about_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
