# Generated by Django 2.2.28 on 2022-08-30 07:55

from django.db import migrations
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()


class Migration(migrations.Migration):

    dependencies = [
        ('kerrokantasi', '0005_add_notified_field'),
    ]

    operations = [
        migrations.RunPython(lambda x,y: User.objects.update(last_login=timezone.now()))
    ]
