name: Kerrokantasi tests

on:
  push:
    branches:
      - release
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: [ ubuntu-20.04 ]
    services:
      postgres:
        image: postgis/postgis:11-2.5
        env:
          POSTGRES_USER: kerrokantasi
          POSTGRES_PASSWORD: kerrokantasi
          POSTGRES_DB: kerrokantasi
          SECRET_KEY: kerrokantasi_secret
          DEBUG: true
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get install gettext python-dev libpq-dev gdal-bin -y
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Apply migrations
        env:
          DATABASE_URL: postgis://kerrokantasi:kerrokantasi@localhost/kerrokantasi
          DEBUG: true
          SECRET_KEY: kerrokantasi_secret
        run: |
          python3 manage.py migrate
      - name: Compile translations
        env:
          DATABASE_URL: postgis://kerrokantasi:kerrokantasi@localhost/kerrokantasi
          DEBUG: true
          SECRET_KEY: kerrokantasi_secret
        run: |
          python3 manage.py compilemessages
      - name: Run tests
        env:
          DATABASE_URL: postgis://kerrokantasi:kerrokantasi@localhost/kerrokantasi
          DEBUG: true
          SECRET_KEY: kerrokantasi_secret
          HEARING_REPORT_PUBLIC_AUTHOR_NAMES: false
          GITHUB_ACTION_TEST: 'true'
        run: |
          pytest
